include: package:flutter_lints/flutter.yaml

analyzer:
  # Exclude generated files
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
    - "lib/generated_plugin_registrant.dart"

  errors:
    # Allow build context usage across async gaps
    use_build_context_synchronously: ignore

    # Treat important issues as errors
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error

linter:
  rules:
    # Performance & Memory
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # Code Quality
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_void: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true

    # Best Practices
    prefer_final_locals: true
    prefer_final_in_for_each: true
    unnecessary_await_in_return: true
    unnecessary_parenthesis: true
    use_super_parameters: true

    # Flutter Specific
    sized_box_for_whitespace: true
    use_build_context_synchronously: false
    avoid_print: true

    # Style
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
